### ISSUE TITLE
密码

### ISSUE THREAD

**Issue by YoonaX** [lxj5957/CLTS-plus-Dataset#1]
您好，可以分享一下Pre-CLTS+ 和 CLTS+ 下载链接的密码吗？邮件给您发了，您还没回复，我的邮箱是tzxiao@ir.hit.edu.cn

**Comment by lxj5957** [comment]
您好！提取密码已发送至您的邮箱，请注意查收！

**Comment by YoonaX** [comment]
好的，谢谢哈~
